### ISSUE TITLE
Change Accessor's count field from i32 to usize

### ISSUE THREAD

**Issue by Mikastiv** [kooparse/zgltf#13]
I was thinking the `count` field of Accessor could be a usize instead of a i32 when adding the iterator. Unless there is a good reason for it to be a signed integer like being part of the spec? It seems to be usize in other gltf libraries I looked at.

**Comment by kooparse** [comment]
The spec says i32, so I'm following the spec on that one! :)

**Comment by Mikastiv** [comment]
@kooparse I looked at the spec and I think it cannot be unsigned (minimum: >= 1)🙂 : https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_accessor_count
