### ISSUE TITLE
`gltf.parse` assumes 4-byte aligned little endian data

### ISSUE THREAD

**Issue by fabioarnold** [kooparse/zgltf#9]
Ran into this because I used `@embedFile` to embed my glb model. Unfortunately, according to https://github.com/ziglang/zig/issues/4680 it's currently not possible to specify alignment for `@embedFile`.

I know it's simpler to just assume these preconditions (and it's probably faster to cast to `u32` pointers). But it would be nice to at least have an assertion for alignment and endianness to help with the error search.

~The safer/correct but also slower way would be to treat the data as a byte stream and use something like this:~
```
var reader = std.io.fixedBufferStream(data).reader();
const my_int = reader.readInt(u32, .little);
```

Edit: nvm, saw in the glTF spec that 4-byte alignment is a requirement. So at least an assertion would be nice.

**Comment by kooparse** [comment]
Thanks, I will see what I can do on this; I'll let you know.

**Comment by fabioarnold** [comment]
Hey, thanks for considering this. And thanks for the great library. It's awesome!

I added `align(4)` to relevant places here:  #10 
Now type-checking will complain when you want to pass unaligned data to `gltf.parse`. What do you think?

I don't know if it's worth it to handle big endian. I think it's a pretty rare these days. I'm targeting wasm, btw.

**Comment by kooparse** [comment]
Merged; thanks a lot! :)
